### ISSUE TITLE
Question: No data about failed requests

### ISSUE THREAD

**Issue by ursenzler** [marcinbudny/applicationinsights-owinextensions#12]
Hi, 

I ask here because I have no clue where else to put this question (other than StackOverflow). Please point me to a better location :-)

I instrumented our ASP.NET Web.Api project with Application Insights. Because we use the OWIN middleware, it did not work until I added your `applicationinsights-owinextensions` package and followed the instructions in the readme.

Now I see requests/sec and request duration inside Application Insights.

However, there is no data about failed calls sent to Application Insights.

Any hint is welcome.

Thanks for your extension!
Urs

**Comment by ursenzler** [comment]
Nevermind, somehow I was able to set a filter in AppInsights that made all data go away %-)

**Comment by marcinbudny** [comment]
Hi Urs,
I'm glad this wasn't a bug in the library :)
