### ISSUE TITLE
SQL Query details are not available in AppInsights

### ISSUE THREAD

**Issue by ursenzler** [marcinbudny/applicationinsights-owinextensions#14]
Not sure whether this really is a concern of your library, but I found no other clue why the SQL statements sent to our Azure SQL server do not show. The dependency details just show the server and the table name.

Everything I found either says to upgrade to .net 4.6 or install Status Monitor - which does not apply for hosting in Azure Web Apps.

Our WebApi runs under .net 4.6 in a Azure Web App with extension ApplicationInsights enabled and connects to a Azure SQL server.

Thanks for your help in advance :-)

**Comment by marcinbudny** [comment]
I noticed this myself some time ago - I used to get SQL command in the logs of my app deployed to Azure Web App and now I don't. Never actually got around to investigating this problem.

To be 100% sure it's not related to the library, I created a clean web application project on .NET 4.6.1 in VS2017, added Application Insights using the default VS integrated tooling and performed a simple SQL query. Still no command logged in AI. I'll look into this more when I find time.

**Comment by Bio2hazard** [comment]
Hey,

I had the same issue and I found the solution. For Azure Web Apps you now need to install application insights directly on the web app via Kudu or Azure Portal.

https://docs.microsoft.com/en-us/azure/application-insights/app-insights-asp-net-dependencies#set-up-dependency-monitoring

If you look at your web app, it's under Extensions, then press the plus and select the App Insights extension. That will bring full dependency information back. Hope that helps!

**Comment by ursenzler** [comment]
Thanks for this solution. In the meantime, we wrote some code on our own that tracks the calls to the database and sends it as normal telemetry to AppInsights. We needed to add some additional data anyway.
