### ISSUE TITLE
When to remove the optional TelemetryInitializers

### ISSUE THREAD

**Issue by Mauzer93** [marcinbudny/applicationinsights-owinextensions#16]
We are using the owin extension, but we have a question about the optional TelemetryInitializers.
In the documentation page, you mention that these can optionally be removed in most cases. 
Can you explain in what cases you cannot remove them? We are using ASP.NET 4.6 with Owin. Can we remove them?

**Comment by marcinbudny** [comment]
To the best of my knowledge, if you are serving all of your requests via Owin, you can remove the TelementryInitializers. This is what I do in my applications. 
You might not want to do this if you have other http handlers, although I haven't confirmed this scenario.

**Comment by Mauzer93** [comment]
Thanks that makes sense!
