### ISSUE TITLE
HTTP 500s not being logged

### ISSUE THREAD

**Issue by ctaggart** [marcinbudny/applicationinsights-owinextensions#17]
When an exception is thrown, the telemetry for the request is not being sent. I'm expecting the request to be logged as a 500. This is pretty critical. 

``` xml
<Add Type="Microsoft.ApplicationInsights.Web.ExceptionTrackingTelemetryModule, Microsoft.AI.Web"/>
```

 is still enabled in `ApplicationInsights.config`, but does not appear to work for OWIN. I didn't see any calls to `TrackException` in this code. Thoughts?

**Comment by marcinbudny** [comment]
Hi Cameron,

This library relies on middlewares you have configured further down the OWIN pipeline to interpret exceptions and turn them into meaningful HTTP statuses. For example WebAPI does this. If you have unhandled exception in your controller, then WebAPI will set the status code to 500. Unless you throw `HttpResponseException` which lets you specify status code yourself.

However if the exception gets as far as `HttpRequestTrackingMiddleware` up the pipeline, then the request will not be correctly logged. This is pretty embarrassing bug. I think the correct behavior in that case is to assume HTTP 500 for the request and log exception telemetry at the same time. I will fix this soon.

**Comment by marcinbudny** [comment]
Package version 0.4.1 will be on nuget soon.

**Comment by ctaggart** [comment]
:gift: I'll see it. I'll be the first one to grab it.

**Comment by ctaggart** [comment]
Just confirming that this is working for us. It logs 500s and the exceptions are linked. Thank you!
