### ISSUE TITLE
Support for DependencyCollector?

### ISSUE THREAD

**Issue by Alexander1967** [marcinbudny/applicationinsights-owinextensions#18]
Hello, 

thanks for your Extension! 
I have a question though: it seems that dependent Downstream calls are not being tracked as Depenedent Calls. My WebApi uses a DLL that in turn makes http-calls to other devices.
From using AI.WCF, I know that these calls can usually be tracked as dependent calls.
How can I achieve this with WebAPI / Owin.Extensions?
I've added the DependentCollector Initializer, but to no avail.

Any idea?

Many thanks!!!
Alexander

**Comment by marcinbudny** [comment]
Hi Alexander,
I'm not sure why you are experiencing this problem. If you take a look at my [integration tests](https://github.com/marcinbudny/applicationinsights-owinextensions/blob/develop/src/ApplicationInsights.OwinExtensions.Tests/OwinIntegrationTests.cs#L79) or the [test website](https://github.com/marcinbudny/applicationinsights-owinextensions/blob/develop/src/TestWebsite/Controllers/ValuesController.cs#L17), you can see I'm specifically testing for the HTTP dependencies being sent. Take a look at the TestWebsite project in general and check if your configuration is similar to mine. If you still have problems, please create a small repro project for me to investigate.

**Comment by Alexander1967** [comment]
Hi Marcin,

 

thanks for getting back to me!

Actually it is working now.

I installed the complete AI packages for Web and restarted my service and all of a sudden I am seeing my dependencies.

I will reinstall piece-by-piece to see exactly which packages need to be present.

 

Kind regards

Alexander

 

 

Gesendet: Montag, 17. April 2017 um 20:08 Uhr
Von: "Marcin Budny" <notifications@github.com>
An: marcinbudny/applicationinsights-owinextensions <applicationinsights-owinextensions@noreply.github.com>
Cc: Alexander1967 <alexander1967@web.de>, Author <author@noreply.github.com>
Betreff: Re: [marcinbudny/applicationinsights-owinextensions] Support for DependencyCollector? (#18)


Hi Alexander,
I'm not sure why you are experiencing this problem. If you take a look at my integration tests or the test website, you can see I'm specifically testing for the HTTP dependencies being sent. Take a look at the TestWebsite project in general and check if your configuration is similar to mine. If you still have problems, please create a small repro project for me to investigate.

**Comment by marcinbudny** [comment]
Closing as this does not seem to be an issue with the library
