### ISSUE TITLE
Assembly Not Signed

### ISSUE THREAD

**Issue by muralikumard** [marcinbudny/applicationinsights-owinextensions#19]
Hi,
I find that these assemblies is unsigned. Any specific reasons for the same?

![unsignedassembly](https://user-images.githubusercontent.com/29543364/27317182-606a9adc-55a2-11e7-8ff3-19b5e6f9e0a8.png)

Since, i am leveraging this nuget in my build, I am facing compliance issues while using this nuget.

Please release a signed (strong named) version of this nuget asap. Thanks in advance!

**Comment by marcinbudny** [comment]
Hi,
Currently all dependencies of this library are strongly signed. However, I want to be able to use unsigned dependencies in the future.
Please explain why you need a signed version.

**Comment by muralikumard** [comment]
Hi Marcin,
I have a security requirement to sign my assembly and hence i have enabled the Signing on my project.
However, since your assembly is unsigned, I get a runtime error like below:

System.IO.FileLoadException: Could not load file or assembly 'ApplicationInsights.OwinExtensions, Version=0.3.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

Would it be possible for you to release a signed version of only this assembly version for now?

Thanks for your help in advance.

**Comment by marcinbudny** [comment]
Hi,
After doing some research among other OSS projects, I'm leaning towards the decision I won't be providing a signed version of this package. This is extra effort, puts constraints on future development and rather few users will benefit from it. See [similar discussion about Akka.NET](https://github.com/akkadotnet/akka.net/issues/957). 

If there are more people interested in signed version, I might reconsider.

For now, I suggest you either fork the library and sign it yourself, or use something like [this auto-signing tool](https://github.com/dsplaisted/strongnamer).
