### ISSUE TITLE
Service Fabric Owin OperationIdContext is null

### ISSUE THREAD

**Issue by OnamChilwan** [marcinbudny/applicationinsights-owinextensions#21]
Seen a couple of issues related to the `OperationId ` being null but they seem to have gone off the grid due to inactivity. I tried using the `RestoreOperationIdContext()` just before `UseWebApi()` however the `id` still remains null. In a nutshell this is what I have:

```
            app.Use<Middleware1>();
            app.Use<Middleware2>();
            app.UseApplicationInsights();
            config.MapHttpAttributeRoutes();
            app.RestoreOperationIdContext();
            app.UseWebApi(config);
```

Thanks.

**Comment by marcinbudny** [comment]
Please create a small repro project for me to work with.

**Comment by OnamChilwan** [comment]
I have managed to get around that problem by utilising the `func` you expose. However, I want to run this `func` conditionally is this possible? I have tried returning an empty `KeyValuePair`, a new `KeyValuePair` with `empty string` as its `key` and `value` and also returned a null but it doesn't seem to like it.

**Comment by OnamChilwan** [comment]
Have a workaround in place whereby I have included an additional `middleware` which adds to the `owin context` and then as part of the `func` you expose I then evaluate the `owin dictionary` and add as necessary. This is because, as part of the `UseApplicationInsights()` you already commit the telemetry data so if I were to commit anything afterwards it would appear as multiple tracks against the request.

In a nutshell it looks like this:

```
app.UseApplicationInsights(getContextProperties: GetContextProperties());
app.Use<Middleware1>();
```

```
        private static Func<IOwinRequest, IOwinResponse, KeyValuePair<string, string>[]> GetContextProperties()
        {
            return (req, res) =>
            {
				object value;

				if (response.Context.Environment.TryGetValue("foo", out value))
				{
					return new KeyValuePair<string, string>("Foo", value.ToString())
				}
                
                return new[] { new KeyValuePair<string, string>(string.Empty, string.Empty) };
            };
        }	
```

```
    public class Middleware1 : OwinMiddleware
    {
        public Middleware1(OwinMiddleware next) : base(next)
        {
        }

        public override async Task Invoke(IOwinContext context)
        {
            if (context.Response.StatusCode == (int)HttpStatusCode.BadRequest)
            {
                context.Response.Environment.Add("foo", "hello world");
            }
        }
    }
```

**Comment by marcinbudny** [comment]
Sorry, but I don't understand how this is related to missing operation id issue. 
It would really help to see some working code that exposes the problem.
