### ISSUE TITLE
Support HTTP Protocol for Correlation

### ISSUE THREAD

**Issue by mikanyg** [marcinbudny/applicationinsights-owinextensions#23]
This article in the [Application Insigts Documentation](https://docs.microsoft.com/en-us/azure/application-insights/application-insights-custom-operations-tracking#incoming-operations-tracking) actually shows an Owin Middleware implementation for HttpRequestTracking that supports the HTTP Protocol for Correlation.

I suggest to add similiar logic to this nuget package.

**Comment by marcinbudny** [comment]
Hi Mikael,
The lib already does something similar, although a bit simplified. See here: https://github.com/marcinbudny/applicationinsights-owinextensions#passing-operationid-via-header

**Comment by mikanyg** [comment]
Yes I did notice that, but it would be a nice feature to have the advanced support with hierarchical correlation ids by setting both the global operation id as well as the parent id foreach depedant request.

Thought that since the article more or less shows the implementation, it would be an easy feature to add.

**Comment by marcinbudny** [comment]
This feature may be implemented in the future, but it seems that first I have to focus on #24 
You are also welcome to contribute a PR.

**Comment by marcinbudny** [comment]
Version 0.6.0 contains changes that should facilitate implementation of mechanisms like HTTP protocol for correlation. However the library will not implement it on its own.
