### ISSUE TITLE
Set requestId and parentId to correlate dependencies to requests in the azure portal 

### ISSUE THREAD

**Issue by Bio2hazard** [marcinbudny/applicationinsights-owinextensions#24]
Right now the dependencies are shown only under "All items for this operation", but not in the request view itself on azure portal.

The reason for that is the portal correlates dependencies to requests based on the dependencies parentId to the requests requestId.

To fix, simply set requestId and parentId to the context Id in `OperationIdTelemetryInitializer.cs`.

The code I use in my own TelemetryInitializer is as follows:
```csharp
    public void Initialize(ITelemetry telemetry)
    {
      var operationId = OperationIdContext.Get();
      if (string.IsNullOrEmpty(operationId)) return;

      telemetry.Context.Operation.ParentId = operationId;

      // Is this a TrackRequest() ?
      if (!(telemetry is RequestTelemetry requestTelemetry)) return;
      requestTelemetry.Id = operationId;
    }
```

I believe requestId is already being set, but I included it just in case.

**Comment by marcinbudny** [comment]
Hi Felix,
Can you explain what do you mean by the "request view"?

**Comment by Bio2hazard** [comment]
When viewing a request on Azure Portal. Right now it shows up like this:

![image](https://user-images.githubusercontent.com/2462038/31355116-d1db67ee-aced-11e7-9e9c-e336ec7f2a89.png)

Note that even though it claims no calls to dependencies were found, in the bottom it does recognize 4 dependency calls.

By setting the ParentId of the dependencies to the operationId, they will be listed properly.

**Comment by marcinbudny** [comment]
I went through [this document](https://docs.microsoft.com/en-us/azure/application-insights/application-insights-correlation) and it seems that the approach of assigning operation id to request id and parent operation id is wrong. I would like to fix it the proper way in the nearest future. There is also #23 which is somewhat related.

**Comment by Bio2hazard** [comment]
The proper way of fixing this would be to dive into the whole parent > child association, but I think at least in the near-term that the scope of such a change is too massive.

You are right about the requestId portion, so instead I would propose checking if the telemetry is of type DependencyTelemetry and assigning the operationId to the parentId if it is.

The example in the document shows that dependencies should use the (request)Id as their parent_operationId:

![image](https://user-images.githubusercontent.com/2462038/31407587-408890aa-adba-11e7-9551-74a618ebf78b.png)

As your package does not track sub-scopes, I maintain that setting the parent_operationId is still the right approach. Especially when you consider the current behavior - it uses the Id generated for the application insights request that's being suppressed.

What I mean is yes - the operationId marks them as part of the operation, but as the request generated by application insights is suppressed, the parent_operationId does not exist, making the dependencies orphaned.

**Comment by marcinbudny** [comment]
I published version 0.5.1 which has a temporary fix that just sets the operation parent id to current operation id. I intend to work some more on this though.

**Comment by marcinbudny** [comment]
Hi Felix,
Please take a look at #25 - I introduced some changes that make it easier to manage the ids of operation and parent operation. It should also enable scenarios like in #23. Requesting comments.

**Comment by marcinbudny** [comment]
Version 0.6.0 containing mentioned changes has been released
