### ISSUE TITLE
Could not install package 'ApplicationInsights.OwinExtensions 0.6.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2'

### ISSUE THREAD

**Issue by PeterRockstars** [marcinbudny/applicationinsights-owinextensions#27]
Hi, 

I'm trying to install the NuGet package but getting this error:

> Could not install package 'ApplicationInsights.OwinExtensions 0.6.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Is it possible to use these extensions with framework version 4.5.2?

**Comment by marcinbudny** [comment]
Hi,
Since version 0.6.0, only .NET Framework 4.6.1+ is supported. You have to either upgrade project to 4.6.1 or use an older version of the library. My mistake is that I didn't state this in the changelog. Will fix it soon.

**Comment by marcinbudny** [comment]
Docs are now fixed
