### ISSUE TITLE
This extension killed my webapp performance

### ISSUE THREAD

**Issue by lahsrah** [marcinbudny/applicationinsights-owinextensions#30]
While doing some load testing I was getting 300 requests / second and when I added this in and used it by doing `app.UseApplicationInsights();`  it killed the performance down to 50 requests / second.

Any idea what is going on?

I can still enable app insights by just setting the instrumentation key like this :
`Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.Active.InstrumentationKey = "mykey";`

**Comment by marcinbudny** [comment]
Hi, 
Two questions:
1. Do you use any telemetry modules or initializers beyond what the library has in it? Check your `ApplicationInsights.config`
1. When you use the AI directly, without this lib, do you get 300 req/s? Do you get the same telemetry?

**Comment by lahsrah** [comment]
1. I am using just the default `ApplicationInsights.config` file, haven't added or removed any Initializers

```
    <TelemetryInitializers>
        <Add Type="Microsoft.ApplicationInsights.DependencyCollector.HttpDependenciesParsingTelemetryInitializer, Microsoft.AI.DependencyCollector"/>
        <Add Type="Microsoft.ApplicationInsights.WindowsServer.AzureRoleEnvironmentTelemetryInitializer, Microsoft.AI.WindowsServer"/>
        <Add Type="Microsoft.ApplicationInsights.WindowsServer.AzureWebAppRoleEnvironmentTelemetryInitializer, Microsoft.AI.WindowsServer"/>
        <Add Type="Microsoft.ApplicationInsights.WindowsServer.BuildInfoConfigComponentVersionTelemetryInitializer, Microsoft.AI.WindowsServer"/>
        <Add Type="Microsoft.ApplicationInsights.Web.WebTestTelemetryInitializer, Microsoft.AI.Web"/>
        <Add Type="Microsoft.ApplicationInsights.Web.SyntheticUserAgentTelemetryInitializer, Microsoft.AI.Web">
                       <Filters>search|spider|crawl|Bot|Monitor|AlwaysOn</Filters>
        </Add>
        <Add Type="Microsoft.ApplicationInsights.Web.ClientIpHeaderTelemetryInitializer, Microsoft.AI.Web"/>
        <Add Type="Microsoft.ApplicationInsights.Web.OperationNameTelemetryInitializer, Microsoft.AI.Web"/>
        <Add Type="Microsoft.ApplicationInsights.Web.OperationCorrelationTelemetryInitializer, Microsoft.AI.Web"/>
        <Add Type="Microsoft.ApplicationInsights.Web.UserTelemetryInitializer, Microsoft.AI.Web"/>
        <Add Type="Microsoft.ApplicationInsights.Web.AuthenticatedUserIdTelemetryInitializer, Microsoft.AI.Web"/>
        <Add Type="Microsoft.ApplicationInsights.Web.AccountIdTelemetryInitializer, Microsoft.AI.Web"/>
        <Add Type="Microsoft.ApplicationInsights.Web.SessionTelemetryInitializer, Microsoft.AI.Web"/>
        <Add Type="ApplicationInsights.OwinExtensions.OperationIdTelemetryInitializer, ApplicationInsights.OwinExtensions"/>

    </TelemetryInitializers>
```

I am still getting AI telemetry without the library, I wasn't using any of the features the library gives yet but just installing it and adding it to my request pipeline seemed to have the said performance impact.   I am not sure if its identical telemetry with and without the library

**Comment by marcinbudny** [comment]
Ok, follow up questions:
1. What is your performance test doing exactly? What endpoints are called and what do they do (simple hello world or actual application code that calls a db, etc.)
2. You need to verify if you get the same telemetry and 300 req/s when not using the lib. Do you get requests and dependencies?

**Comment by lahsrah** [comment]
1. Yeah its a simple hello world type of test, just returns a string, no resources like db etc.
```
        public IHttpActionResult Get()
        {
            return Ok("Hello World");
        }
```
2. Yes I am getting telemetry, requests, dependencies, exceptions etc

**Comment by marcinbudny** [comment]
Using a simple "Hello world" may be the reason you see this performance drop. The overhead of creating telemetry is significant compared to super fast operation of returning a string constant.  If you ran another test with more real-life endpoint, you'd probably experience less relative perf drop.

That being said, I should also mention the lib was never optimized for performance. I also do not plan any work in this field, because Owin is now superseded with ASP.NET Core pipeline and the problems this lib solved are not present there.
