### ISSUE TITLE
How to set the user context of RequestTelemetry

### ISSUE THREAD

**Issue by mm-set** [marcinbudny/applicationinsights-owinextensions#31]
I do not find a way to set the user context of the `RequestTelemetry`. I can get the user information out of the Owin context. Adding it to the additional context properties like this works:

            appBuilder.UseApplicationInsights(new RequestTrackingConfiguration
            {
                GetAdditionalContextProperties = owinContext =>
                {
                    var additionalProperties = new List<KeyValuePair<string, string>>();

                    if (owinContext.Request.User is ClaimsPrincipal claimsPrincipal)
                    {
                        var userId = claimsPrincipal.GetUserId().ToString();
                        additionalProperties.Add(new KeyValuePair<string, string>("UserId", userId));
                    }

                    return Task.FromResult(additionalProperties.AsEnumerable());
                }
            });

Unfortunately, this results in the UserId being part of the custom data. I.e. the User tracking of App Insights will not be populated.

Is there any way to set the built-in user context of the `RequestTelemetry` object?

**Comment by marcinbudny** [comment]
Hi,
With current functionality this is not possible. If I find some time, I might add something that will enable this scenario. You can also submit a PR.
