### ISSUE TITLE
ApplicationInsights.OwinExtensions.HttpRequestTrackingMiddleware+<Invoke>d__4.MoveNext

### ISSUE THREAD

**Issue by arunbalajip** [marcinbudny/applicationinsights-owinextensions#36]
SDK version:
"ApplicationInsights.OwinExtensions" Version="0.6.0"
"Microsoft.ApplicationInsights" Version="2.8.1"
"Microsoft.ApplicationInsights.DependencyCollector" Version="2.8.1"
"Microsoft.ApplicationInsights.PerfCounterCollector" Version="2.8.1"
"Microsoft.ApplicationInsights.Web" Version="2.8.1"
"Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel" Version="2.8.1"
"Microsoft.AspNet.WebApi.Owin" Version="5.2.6"

.NET runtime version (.NET or .NET Core, TargetFramework in the .csproj file):
Microsoft.NET Framework 4.6.1

Hosting Info (IIS/Azure WebApps/etc):
Azure Service Fabric

Describe exactly how to reproduce the error. Include a code sample if applicable.
We are listening to external dependency using Application insights. we are getting errors in OWIN listener package.

we are capturing the external calls. We also get these errors too.

Additional context.

![image](https://user-images.githubusercontent.com/20033858/81354598-e6c36480-9080-11ea-8688-121a48f8e3e1.png)

ApplicationInsights.config
https://github.com/arunbalajip/Issues/blob/master/ApplicationInsights.config

**Comment by marcinbudny** [comment]
Moving all discussion to #20
