### ISSUE TITLE
Expose TelemetryClient?

### ISSUE THREAD

**Issue by hastarin** [marcinbudny/applicationinsights-owinextensions#5]
First I'm new to Application Insights so I could be totally off base here.

The problem I'm trying to solve is I'd like to be able to record things like the User Id, Device Id, etc for each request.

I'm presuming/hoping that if you exposed TelemetryClient, or allow it to be passed in to the constructor for the middleware, I could then modify those properties during the pipeline to add those details?

Eg.  I've created a static TelemetryClient within my OWIN Service that I then update via an AuthenticationFilter.  This is logged via Traces (I'm using Serilog.Sinks.ApplicationInsights so my logging automatically gets traced) but obviously not along with the Requests that your extension is providing.

**Comment by marcinbudny** [comment]
Hi,
It's not the `TelemetryClient` you should be interested in, but rather the `TelemetryConfiguration`. All client instances use the same configuration by default `TelemetryConfiguration.Active`, however you can specify another configuration if you wish.

The `HttpRequestTrackingMiddleware` allows you to pass in the `TelemetryConfiguration`. I suggest you pass the same `TelemetryConfiguration` instance to the middleware and the Serilog sink. In this configuration you register your telemetry initializer recording UserId, DeviceId, etc. These properties should be bound to the context of a request. Could be stored in Owin environment dictionary or the LogicalContext.

**Comment by hastarin** [comment]
I'll have to look into that then.  In the [Serilog sink](https://github.com/serilog/serilog-sinks-applicationinsights) I'm using that common `TelemetryClient` which I also use to [Flush ](https://azure.microsoft.com/en-us/documentation/articles/app-insights-api-custom-events-metrics/#flushing-data) things on shutdown of the Owin service.

From what you're saying I'll need to look at a custom [ContextInitializer](https://msdn.microsoft.com/en-us/library/microsoft.applicationinsights.extensibility.telemetryconfiguration.contextinitializers.aspx) though I'm not sure how that helps me get access to the context when I need to update it (ie upon authentication)?

I feel like I've been thrown in the deep end between a limited understanding of the OWIN pipeline and now ApplicationInsights which is why I've used your library (thanks for it BTW) in the first place.  :)

**Comment by marcinbudny** [comment]
On second thought, if you're using Serilog anyway, you could try using the [LogContext](https://github.com/serilog/serilog/wiki/Enrichment#the-logcontext) to enrich the logged events with properties like UserId. You would have to create a middleware that opens the scope once UserId is known. This is event better than doing this for AI alone, because the properties will be logged to all Serilog sinks, not only the AI one.

**Comment by hastarin** [comment]
I am not really after that information with the logging context. I'd prefer
it with AI so I can easily report on it via analytics, create dashboards etc

**Comment by marcinbudny** [comment]
Serilog AI sink will write all the properties in a structured manner in the same way you would do this using TelemetryClient directly. The only limitation is that you have to choose whether you are logging Traces or Events to AI.

**Comment by hastarin** [comment]
But they aren't directly associated with the request which already has a
user_id, etc that just isn't getting populated in the OWIN hosted situation
like it would in ASP.NET. I'm trying to see exactly which users are doing
what on the API without resorting to logging extra custom events/traces.

**Comment by hastarin** [comment]
So I managed to set my custom principal in the Owin Environment, but I can't see any way to access that via a TelemetryInitializer, or any way to use it with your project without creating my own custom version.

Any hints/ideas would be most appreciated?

```
                            context.Principal = user;
                            var owinEnviroment = context.Request.GetOwinContext().Environment;
                            if (owinEnviroment != null)
                            {
                                var key = "AuthenticatedUser";
                                if (!owinEnviroment.ContainsKey(key))
                                {
                                    owinEnviroment.Add(key, user);
                                }
                                else
                                {
                                    owinEnviroment[key] = user;
                                }
                            }
```

**Comment by hastarin** [comment]
I ended up creating my own `HttpRequestTrackingAuthenticatedUserMiddleware` based on your `HttpRequestTrackingMiddleware` which seems to do the trick for now.  I'm not sure it's the ideal solution but it's all I could get working.
